### ISSUE TITLE
visual feature file

### ISSUE THREAD

**Issue by Leavelk** [jingchenchen/ReasoningConsistency-VQA#2]
Hello, there is always a network error when downloading the visual feature file. Is there any other download method? Thanks!

**Comment by jingchenchen** [comment]
I am tring to upload the features to Baidu Cloud. But it may take some time.

**Comment by jingchenchen** [comment]
> Hello, there is always a network error when downloading the visual feature file. Is there any other download method? Thanks!
To download the features form the current url, you should make sure you can access websites such as google scholar.

**Comment by Leavelk** [comment]
> > Hello, there is always a network error when downloading the visual feature file. Is there any other download method? Thanks!
> > To download the features form the current url, you should make sure you can access websites such as google scholar.

Yes, I can access it, but still, the same error occurs. I can wait to download it from Baidu Cloud, thanks for your help and the great work!

**Comment by jingchenchen** [comment]
> > > Hello, there is always a network error when downloading the visual feature file. Is there any other download method? Thanks!
> > > To download the features form the current url, you should make sure you can access websites such as google scholar.
> 
> Yes, I can access it, but still, the same error occurs. I can wait to download it from Baidu Cloud, thanks for your help and the great work!

If you haven't downloaded the features successfully, please try the following link.  
https://pan.baidu.com/s/1vSmi3xvqXG5ETFZv8NUqWw  
code:  ageh

**Comment by Leavelk** [comment]
Thank you very much! I have downloaded the features successfully 😄！
