### ISSUE TITLE
子问题的生成

### ISSUE THREAD

**Issue by LemonQC** [jingchenchen/ReasoningConsistency-VQA#3]
您好，请问您的子问题生成是采用程序实现的么，还是人工根据语义图去生成的？

**Comment by jingchenchen** [comment]
你好，子问题是使用程序根据图像的场景图来自动生成的，不需要人工，具体细节可以参考论文的4.1节。

**Comment by LemonQC** [comment]
哦哦，不知道您是否可以开放这个提取生成的代码呢

**Comment by jingchenchen** [comment]
问题生成方面我们借鉴了gqa数据集的思路，这部分不是我们的主要创新点，所以我们目前没有release这部分代码的计划。关于问题生成的细节，如果有什么疑问可以随时交流，github 或者邮件都可以的。

**Comment by LemonQC** [comment]
好的，谢谢您的回复


| |
Shandong University
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Chenchen ***@***.***> |
| 发送日期 | 2022年9月15日 19:21 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [jingchenchen/ReasoningConsistency-VQA] 子问题的生成 (Issue #3) |

问题生成方面我们借鉴了gqa数据集的思路，这部分不是我们的主要创新点，所以我们目前没有release这部分代码的计划。关于问题生成的细节，如果有什么疑问可以随时交流，github 或者邮件都可以的。
