### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by Wiikk** [jingchenchen/ReasoningConsistency-VQA#4]
Hi, thanks for your excellent work!

I noticed the GPU utilization is very low. How much time did it take to train one epoch in your standard single-GPU setting, and is there any advice to accelerate the training process? Thanks a lot.

**Comment by jingchenchen** [comment]
Training the network for one epoch takes about one hour with a single rtx 3090. It would be helpful to put the visual features on a SSD disk.

**Comment by Wiikk** [comment]
Alright, thank you.
