### ISSUE TITLE
The annotations.

### ISSUE THREAD

**Issue by LemonQC** [jingchenchen/ReasoningConsistency-VQA#5]
![image](https://user-images.githubusercontent.com/30914380/226363294-8804029b-76e9-45ff-99aa-0f9cf46abcb9.png)

In the validation.json,
    "18168879_0": {
        "question": "Is there a ball that is to the right of the racket?",
        "imageId": "61533",
        "answer": "yes",
        "step": 2
    },
I only found one question. Why the step is set to 2?

**Comment by jingchenchen** [comment]
The step means the required itereations instead of the number of sub-questions. 
"Specifically, the number of iterations Tq is determined by performing Part-of-speech (POS) tagging for the question via the Spacy tool [7] and computing the number of nouns in it." (Sec.3.1)

**Comment by LemonQC** [comment]
Where can I find the Qualitative examples? I try to search it in val.json. However, I can not find.

**Comment by jingchenchen** [comment]
The "val_balanced_questions.json" contains compositional questions, while the "val_sub_balanced_questions.json" contains the  sub-questions. The qualitative examples can be found in the two files. Please see the question (13471154) of the "val_balanced_questions.json".

**Comment by jingchenchen** [comment]
Marking this issue as resolved. Feel free to reopen if you have any more questions.
