### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by wangfan807** [jingchenchen/ReasoningConsistency-VQA#7]
Is there another way to download the visual dataset? It disconnects halfway through the download in this link.

**Comment by jingchenchen** [comment]
Please try the following link. :)
链接：https://pan.baidu.com/s/1ovqHf5jebmyRYHyzHumBSw 
提取码：j12h

**Comment by wangfan807** [comment]
下载后训练，显示缺少部分数据。想问一下是什么原因？


19862113130王璠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingchenchen/ReasoningConsistency-VQA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月12日(星期二) 晚上6:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jingchenchen/ReasoningConsistency-VQA] datasets (Issue #7)





 
Please try the following link. 链接：https://pan.baidu.com/s/1ovqHf5jebmyRYHyzHumBSw
 提取码：j12h:

**Comment by jingchenchen** [comment]
A possible reason is that the downloaded data is incomplete. Please make sure that a total of 148852 files have been downloaded.

**Comment by wangfan807** [comment]
您好，我从您网盘下载下来的数据集只有65000个项目，我确保我的电脑容量是足够下载的。所以还有什么其他的原因吗？



---Original---
From: "Chenchen ***@***.***&gt;
Date: Thu, Sep 14, 2023 22:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jingchenchen/ReasoningConsistency-VQA] datasets (Issue #7)




 
A possible reason is that the downloaded data is incomplete. Please make sure that a total of 148852 files have been downloaded.

**Comment by jingchenchen** [comment]
I'm sure there are over 140,000 files in that folder. I suggest save the file to Baidu NetDisk and checking the number of files in the software. If necessary, please re-download the files.

**Comment by fuyongxu0908** [comment]
Can you share the Baidu Netdisk link again, tks.

**Comment by jingchenchen** [comment]
The following is the new link.  :)
链接：https://pan.baidu.com/s/1WRTcoJ_ItyyNkToqNkw_GQ 
提取码：8ibf

**Comment by fuyongxu0908** [comment]
Good work, tks again.
